package com.vobi.team.modelo;
// Generated 7/05/2016 11:16:36 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * VtProgresoArtefacto generated by hbm2java
 */
public class VtProgresoArtefacto  implements java.io.Serializable {


     private Long proartCodigo;
     private VtArtefacto vtArtefacto;
     private Integer esfuerzoRestante;
     private Integer esfuerzoReal;
     private Integer puntos;
     private Integer tiempoDedicado;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;

    public VtProgresoArtefacto() {
    }

	
    public VtProgresoArtefacto(Long proartCodigo, Integer esfuerzoRestante, Integer esfuerzoReal, Integer puntos, Integer tiempoDedicado, String descripcion, Date fechaCreacion, Long usuCreador, String activo) {
        this.proartCodigo = proartCodigo;
        this.esfuerzoRestante = esfuerzoRestante;
        this.esfuerzoReal = esfuerzoReal;
        this.puntos = puntos;
        this.tiempoDedicado = tiempoDedicado;
        this.descripcion = descripcion;
        this.fechaCreacion = fechaCreacion;
        this.usuCreador = usuCreador;
        this.activo = activo;
    }
    public VtProgresoArtefacto(Long proartCodigo, VtArtefacto vtArtefacto, Integer esfuerzoRestante, Integer esfuerzoReal, Integer puntos, Integer tiempoDedicado, String descripcion, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo) {
       this.proartCodigo = proartCodigo;
       this.vtArtefacto = vtArtefacto;
       this.esfuerzoRestante = esfuerzoRestante;
       this.esfuerzoReal = esfuerzoReal;
       this.puntos = puntos;
       this.tiempoDedicado = tiempoDedicado;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
    }
   
    public Long getProartCodigo() {
        return this.proartCodigo;
    }
    
    public void setProartCodigo(Long proartCodigo) {
        this.proartCodigo = proartCodigo;
    }
    public VtArtefacto getVtArtefacto() {
        return this.vtArtefacto;
    }
    
    public void setVtArtefacto(VtArtefacto vtArtefacto) {
        this.vtArtefacto = vtArtefacto;
    }
    public Integer getEsfuerzoRestante() {
        return this.esfuerzoRestante;
    }
    
    public void setEsfuerzoRestante(Integer esfuerzoRestante) {
        this.esfuerzoRestante = esfuerzoRestante;
    }
    public Integer getEsfuerzoReal() {
        return this.esfuerzoReal;
    }
    
    public void setEsfuerzoReal(Integer esfuerzoReal) {
        this.esfuerzoReal = esfuerzoReal;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Integer getTiempoDedicado() {
        return this.tiempoDedicado;
    }
    
    public void setTiempoDedicado(Integer tiempoDedicado) {
        this.tiempoDedicado = tiempoDedicado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }




}


